---
language: go
sudo: false

go:
  - 1.12
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://microsoftgoproxy.azurewebsites.net/

install: make deps
script: make statik all
notifications:
    email: false
